#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          xmlrcsd
# Required-Start:    $remote_fs $syslog $redis
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: xmlrcsd
### END INIT INFO

# Author: Petr Bena <benapetr@gmail.com>

DESC="XmlRcs provider"
DAEMON=/home/xmlrcs/xmlrcsd
PIDFILE=/var/run/xmlrcs.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
        log_daemon_msg "Starting $DESC"
        start_daemon -p $PIDFILE  -g xmlrcs -u xmlrcs $DAEMON
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping $DESC"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON atd && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/atd {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
